default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USER_NAME") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>
  timeout: 5000

development:
  <<: *default
  database: living_room_development

test:
  <<: *default
  database: living_room_test

production:
  <<: *default
  database: living_room_production
  username: living_room
  password: <%= ENV['LIVING_ROOM_DATABASE_PASSWORD'] %>
