default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PG_USER_NAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  timeout: 5000

development:
  <<: *default
  database: living_room_development

test:
  <<: *default
  database: living_room_test

staging:
  <<: *default
  database: living_room_staging

production:
  <<: *default
  database: living_room_production
  username: <%= ENV["PG_PRODUCTION_USER_NAME"] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>
